# cronjobs/etf_forecast_cron.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-etf-forecast
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: forecast-job
            image: my-docker-registry/etf-predict:latest
            command: ["python", "pipeline/train_all.py"]
          restartPolicy: OnFailure
